//! CLI arguments for the webshotd server.

// Re-exported so `Args::parse()` resolves from code generated by
// the derive macro, i.e. `Args::parse()` works without importing `clap`
pub use clap::Parser;
use std::{net::SocketAddr, path::PathBuf};

/// Command-line arguments for the webshotd server.
///
/// Default values assume a single shared browser instance serving
/// local requests only.
#[derive(Debug, Parser)]
#[command(version)]
pub struct Args {
    //--- Browser
    /// Path to the chromium executable
    #[arg(long)]
    pub chromium_path: PathBuf,

    /// Path to the chromium profile directory
    #[arg(long)]
    pub user_data_dir: PathBuf,

    /// Run the browser in headless mode
    #[arg(long)]
    pub headless: bool,

    /// Run the browser in incognito mode
    #[arg(long)]
    pub incognito: bool,

    //--- Server
    /// Socket address for the server to listen on
    #[arg(long, default_value = "127.0.0.1:7468")]
    pub addr: SocketAddr,

    /// Maximum number of concurrent browser tasks
    #[arg(long, default_value_t = 20)]
    pub concurrency: usize,

    /// Request timeout in milliseconds
    #[arg(long, default_value_t = 20_000)]
    pub timeout_ms: u32,

    /// Maximum number of frames per page
    #[arg(long, default_value_t = 20)]
    pub max_frames: u32,

    /// Directory for generated images
    #[arg(long, default_value = "/tmp/webshotd")]
    pub image_dir: PathBuf,
}
